/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffebucks;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Pedido;
import model.bean.Usuario;
import model.dao.PedidoDAO;

/**
 *
 * @author David
 */
public final class TelaPesquisa extends javax.swing.JInternalFrame {

   Usuario usuario=null;
    public TelaPesquisa(Usuario usuario) {
        initComponents();
         DefaultTableModel modelo = (DefaultTableModel) jTableDesc.getModel();
        jTableDesc.setRowSorter(new TableRowSorter(modelo));

       readJTable();
         this.usuario = usuario;
    }
public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTableDesc.getModel();
        modelo.setNumRows(0);
        PedidoDAO pdao = new PedidoDAO();

        for (Pedido p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getId_pedido(),
                p.getId_usuario(),
                p.getDescricao(),
                p.getQuantidade(),
                p.getPreco(),
                p.getData()
            });

        }

    }
public void readJTableForDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTableDesc.getModel();
        modelo.setNumRows(0);
        PedidoDAO pdao = new PedidoDAO();

        for (Pedido p : pdao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
               p.getId_pedido(),
                p.getId_usuario(),
                p.getDescricao(),
                p.getQuantidade(),
                p.getPreco(),
                p.getData()
            });

        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDesc = new javax.swing.JTextField();
        jTextFieldQuant = new javax.swing.JTextField();
        jTextFieldPreco = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDesc = new javax.swing.JTable();

        setClosable(true);
        setTitle("Estoque");

        jLabel1.setText("Descrição");

        jLabel2.setText("Quantidade");

        jLabel3.setText("Preço");

        jTextFieldPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecoActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(483, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
        );

        jTableDesc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_pedido", "ID_usuario", "Descrição", "Quantidade", "Preço", "Data"
            }
        ));
        jTableDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableDescKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDesc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        Pedido p = new Pedido();
        PedidoDAO dao = new PedidoDAO();
        p.setId_usuario(this.usuario.getId());
        p.setDescricao(jTextFieldDesc.getText());
        p.setQuantidade(Integer.parseInt(jTextFieldQuant.getText()));
        p.setPreco(Double.parseDouble(jTextFieldPreco.getText()));
        dao.create(p);
         jTextFieldDesc.setText("");
            jTextFieldQuant.setText("");
            jTextFieldPreco.setText("");
        readJTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecoActionPerformed

    private void jTableDescKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableDescKeyReleased
           if (jTableDesc.getSelectedRow() != -1) {

            jTextFieldDesc.setText(jTableDesc.getValueAt(jTableDesc.getSelectedRow(), 1).toString());
            jTextFieldQuant.setText(jTableDesc.getValueAt(jTableDesc.getSelectedRow(), 2).toString());
            jTextFieldPreco.setText(jTableDesc.getValueAt(jTableDesc.getSelectedRow(), 3).toString());

        }
    }//GEN-LAST:event_jTableDescKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if (jTableDesc.getSelectedRow() != -1) {
        Pedido p = new Pedido();
        PedidoDAO dao = new PedidoDAO();

        p.setDescricao(jTextFieldDesc.getText());
        p.setQuantidade(Integer.parseInt(jTextFieldQuant.getText()));
        p.setPreco(Double.parseDouble(jTextFieldPreco.getText()));
        p.setId_pedido((int)jTableDesc.getValueAt(jTableDesc.getSelectedRow(), 0));
        p.setId_usuario((int)jTableDesc.getValueAt(jTableDesc.getSelectedRow(), 0));
        dao.update(p);
         jTextFieldDesc.setText("");
            jTextFieldQuant.setText("");
            jTextFieldPreco.setText("");
        readJTable();
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if (jTableDesc.getSelectedRow() != -1) {

            Pedido p = new Pedido();
            PedidoDAO dao = new PedidoDAO();

            p.setId_pedido((int) jTableDesc.getValueAt(jTableDesc.getSelectedRow(), 0));
             p.setId_usuario((int)jTableDesc.getValueAt(jTableDesc.getSelectedRow(), 1));
            dao.delete(p);

            jTextFieldDesc.setText("");
            jTextFieldQuant.setText("");
            jTextFieldPreco.setText("");

            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDesc;
    private javax.swing.JTextField jTextFieldDesc;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldQuant;
    // End of variables declaration//GEN-END:variables


}
